### ISSUE TITLE
FasterGUI actually makes the FPS graph render slower

### ISSUE THREAD

**Issue by QPCrummer** [tr7zw/FasterGUI#10]
![image](https://user-images.githubusercontent.com/66036033/180303017-69a76a29-db1f-4b42-af9d-dc976126d7da.png)
The Alt + F3 graph actually renders at the set FPS in the config, which could be a real issue for debugging performance issues.

**Comment by tr7zw** [comment]
I mean, that is kind of the entire point of this mod^^? If it's an issue unrelated to the mod, you can temporarily disable it in the config to get the graph again in real-time. 
Related:
Another issue I've encountered is that this graph breaks at too high framerates, so as a side project of this mod, https://github.com/tr7zw/GraphUtil was created. It modifies this graph to show everything with decimal points and without rounding and can scale the graph so the bottom is the min ms and the top is the max ms(so you can debug even 0.1-2ms framerates). A future planned feature of that mod is to make this graph fps independent(since at 240fps the entire graph gets refreshed once per second, at 480 fps twice a second etc), add 0.99% percentiles, and so on, so the graph can become actually useful.
